# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668728b6ada9b84895b70942cb8d59707fb61f72c41bb38a673c90556b4a8bd0ae23fe1573b641a7dd9cbbc587c085e5935b21a61b54bd795eae841f64666fd7

test:
  secret_key_base: 0a48faf1415bf5232d80b1b85b133f83c8fb7f8fa6b61e72ccc674f261626a492c9bd71223105e2a8511fa28b666d751355d42661360701942f64288bc97179b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
